### ISSUE TITLE
让 surfingkeys 使用 cnbtkitty 关键字搜索 能做到否？

### ISSUE THREAD

**Issue by ghost** [chanket/MagnetX#1]
[surfingkeys 是chrome扩展](https://chrome.google.com/webstore/detail/surfingkeys/gfbliohnnapiefjpjlpjnehglfpaknnc)

**Comment by chanket** [comment]
对surfingkeys不太了解。不过cnbtkitty的关键词处理完全可以通过JavaScript复现：
1. 关键词转换成二进制序列（UTF8编码）
2. 二进制用Deflate算法压缩。
3. 压缩结果用Base64字符串表示。
4. 将Base64转换为URL友好的形式，也就是/替换为-，+替换为-，去掉末尾=。

[这个项目](https://github.com/dankogai/js-deflate)已经做好了上述1-3的工作。

**Comment by chanket** [comment]
笔误，/替换为_
